---
title: "Figure 1 - MutSpot Workflow"
output: html_document
---

This is the R Markdown for Figure 1, which consists of 5 parts.

```{r, echo = FALSE}
suppressWarnings(suppressMessages(library(MutSpot)))
suppressWarnings(suppressMessages(library(GenomicRanges)))
suppressWarnings(suppressMessages(library(ggplot2)))
```

## Figure B
Gastric whole genome SNV MutSpot results
```{r, eval = FALSE}
# Run MutSpot
MutSpot(snv.mutations = "gastric_snv_mutations_sid.MAF", cores = 6, cutoff.nucleotide.new = 1, drop = TRUE, genomic.features = "genomic_features_genome_APO.txt")
```

```{r}
hotspots = read.delim("snv_wgs_hotspots_merged.tsv", stringsAsFactors = FALSE)

# Adjust manhattan plot cutoff from fdr 0.1 to fdr 0.05 and save as SVG with height = 4 and width = 9
plot_manhattan(hotspots.file = hotspots, fdr.cutoff = 0.05, color.line = "red", color.dots = "maroon1")
```

## Figure C
Gastric CTCF binding sites SNV MutSpot results
```{r, eval = FALSE}
# Run MutSpot
MutSpot(snv.mutations = "gastric_snv_mutations_sid.MAF", region.of.interest = "gastric_ctcf_motif.bed", cores = 6, drop = TRUE, sample.snv.features = "sample_features_table_snv.txt", genomic.features = "genomic_features_ctcf_APO.txt")
```

```{r}
hotspots = read.delim("snv_ctcf_hotspots_merged.tsv", stringsAsFactors = FALSE)

# Adjust manhattan plot cutoff from fdr 0.1 to fdr 0.05 and save as SVG with height = 4 and width = 9
plot_manhattan(hotspots.file = hotspots, fdr.cutoff = 0.05, color.line = "red", color.dots = "maroon1")
```

## Figure D
Barplot for gastric whole genome SNV model comparison
```{r, eval = FALSE}
# Run simple binomial model
mask.regions.file = "mask_regions.RDS"
snv.mutations.file = "gastric_snv_mutations_sid.MAF"
snv.mutations.file2 = "gastric_snv_mutations_sid.MAF"
cores = 4
region.of.interest = NULL

chrOrder <- c(paste("chr", 1:22, sep = ""), "chrX")
seqi = GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[GenomeInfoDb::seqnames(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[1:23]]
seqnames = GenomeInfoDb::seqnames(GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens))[1:23]

mask.regions = readRDS(mask.regions.file)
mask.regions = mask.regions[as.character(GenomeInfoDb::seqnames(mask.regions)) %in% seqnames]

maf.snv <- maf.to.granges(snv.mutations.file)
maf.snv = maf.snv[as.character(GenomeInfoDb::seqnames(maf.snv)) %in% seqnames]
GenomeInfoDb::seqlevels(maf.snv) = as.character(unique(GenomeInfoDb::seqnames(maf.snv)))

maf.snv2 <- maf.to.granges(snv.mutations.file2)
maf.snv2 = maf.snv2[as.character(GenomeInfoDb::seqnames(maf.snv2)) %in% seqnames]
maf.ind.snv = GenomicRanges::split(maf.snv2, maf.snv2$sid)
ind.mut.count.snv = sapply(maf.ind.snv, length)

maf.masked.snv <- maf.snv[-S4Vectors::subjectHits(IRanges::findOverlaps(mask.regions, maf.snv))]
dupl.snv = duplicated(maf.masked.snv)
maf.uniq.snv = maf.masked.snv[!dupl.snv, ]

mut.regions = maf.uniq.snv + 10
names(mut.regions) = paste("Mutation", c(1:length(mut.regions)), sep = "")

rm(list = c("maf.uniq.snv", "mask.regions"))
gc()

genome.size = 2533374732
roi = mut.regions

print(paste("Using ", length(roi), " ROIs from input", sep = ""))

print(">> Intersecting ROIs and MAF ...")
maf.ovl <- IRanges::findOverlaps(roi, maf.snv, ignore.strand = TRUE)
maf.ovl.m = IRanges::as.matrix(maf.ovl)
min.count = 2

nsamples = length(unique(maf.snv$sid))
roi.count.mutated = tapply(maf.snv$sid[maf.ovl.m[ ,2]], names(roi)[maf.ovl.m[ ,1]],function(s) length(unique(s)))
roi.mutated = names(roi.count.mutated)[roi.count.mutated >= min.count]
print(paste("Using ", length(roi.mutated), " ROIs mutated in >=", min.count, " samples", sep = ""))

rois.to.run = roi.mutated

results = c()

sid=unique(maf.snv2$sid)

p.bg = parallel::mclapply (sid, function(s) {
  
  p = rep(length(maf.snv2) / (2533374732 * (length(unique(maf.snv2$sid)))), 21)
  p.roi.snv = 1 - prod(1 - p)   
  
  return(p.roi.snv)
  
}, mc.cores = 4 )
p.bg = unlist(p.bg)

process.single.roi <- function(x) {
  
  roi.progress <- which(rois.to.run == x)
  if ((roi.progress %% ceiling(length(rois.to.run) / 1000)) == 0) {
    
    print(paste("Progress : ", roi.progress, "/", length(rois.to.run), sep = ""))
    
  }
  
  x.idx = which(names(roi) == x)[1]
  k = length(unique(maf.snv$sid[maf.ovl.m[maf.ovl.m[ ,1] == x.idx, 2]]))
  
  pval = 1 - pbinom(k - 1, 168, unique(p.bg))
  
  c(x, pval, 21, mean(p.bg), k)
  
}

results = parallel::mclapply(rois.to.run, function(xr) { process.single.roi(xr) }, mc.cores = cores, mc.preschedule = FALSE, mc.silent = FALSE)

results.error = sapply(results, function(x) { length(x) == 1 } )
print(rois.to.run[which(results.error)])
print(results[results.error])
results = results[!results.error]

results = do.call(rbind,results)
rownames(results) = results[ ,1]
results = results[ ,-1, drop = FALSE]
class(results) <- "numeric"
fdr = p.adjust(results[ ,1], method = 'BH') * genome.size / nrow(results)
fdr = sapply(fdr, function(x) min(x, 1))  
results = cbind(results, fdr)
colnames(results) = c('pval', 'length', 'p.bg', 'k', 'fdr')
results = results[order(results[ ,'pval']), , drop = FALSE]

mut.rec = results
mut.regions2 = mut.regions[names(mut.regions) %in% rownames(mut.rec)]
mut.rec.hotspot = data.frame(chrom = as.character(GenomeInfoDb::seqnames(mut.regions2[rownames(mut.rec)])), start = GenomicRanges::start(mut.regions2[rownames(mut.rec)]), end = GenomicRanges::end(mut.regions2[rownames(mut.rec)]), mut.rec)

write.table(mut.rec.hotspot, file = "wgs_hotspots_null1.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = TRUE)

mut.rec.hotspot2 = mut.rec.hotspot
mut.rec.hotspot2$ID = as.character(rownames(mut.rec.hotspot2))
mut.rec.hotspot2 = with(mut.rec.hotspot2, GenomicRanges::GRanges(chrom, IRanges::IRanges(start, end), pval = pval, length = length, p.bg = p.bg, k = k, fdr = fdr, ID = ID))
hotspots = IRanges::reduce(mut.rec.hotspot2)
hotspots$hs = paste("hs", 1:length(hotspots), sep = "")
ovl.mut = IRanges::findOverlaps(maf.snv, hotspots)
hotspots2 = hotspots[S4Vectors::subjectHits(ovl.mut)]
hotspots2$sample = maf.snv[S4Vectors::queryHits(ovl.mut)]$sid
hotspots2 = GenomicRanges::as.data.frame(hotspots2)
hotspots2 = aggregate(sample ~ hs, hotspots2, FUN = function(k) length(unique(k)))
colnames(hotspots2)[2] = "k"
rownames(hotspots2) = hotspots2$hs
hotspots$k = 0
for (i in 1:length(hotspots)) {
  # print(i)
  hotspots$k[i] = hotspots2[which(hotspots2$hs == hotspots$hs[i]), "k"]
  
}

ovl = IRanges::findOverlaps(mut.rec.hotspot2, hotspots)
mut.rec.hotspot2 = mut.rec.hotspot2[S4Vectors::queryHits(ovl)]
mut.rec.hotspot2$hs = hotspots[S4Vectors::subjectHits(ovl)]$hs
mut.rec.hotspot2$region.start = IRanges::start(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$region.end = IRanges::end(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$new.k = hotspots[S4Vectors::subjectHits(ovl)]$k
mut.rec.hotspot2 = GenomicRanges::as.data.frame(mut.rec.hotspot2)
mut.rec.hotspot2 = mut.rec.hotspot2[order(mut.rec.hotspot2$pval, decreasing = FALSE), ]
mut.rec.hotspot2 = mut.rec.hotspot2[!duplicated(mut.rec.hotspot2$hs), ]
mut.rec.hotspot2 = mut.rec.hotspot2[ ,c("seqnames", "region.start", "region.end", "pval", "length", "p.bg", "new.k", "fdr", "ID")]
mut.rec.hotspot2$length = mut.rec.hotspot2$region.end - mut.rec.hotspot2$region.start + 1
colnames(mut.rec.hotspot2) = c(colnames(mut.rec.hotspot), "ID")
rownames(mut.rec.hotspot2) = mut.rec.hotspot2$ID
mut.rec.hotspot2 = mut.rec.hotspot2[ ,-ncol(mut.rec.hotspot2)]

write.table(mut.rec.hotspot, file = "wgs_hotspots_null1_merged.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = TRUE)
```

```{r, eval = FALSE}
# Run poisson binomial model
mask.regions.file = "mask_regions.RDS"
snv.mutations.file = "gastric_snv_mutations_sid.MAF"
snv.mutations.file2 = "gastric_snv_mutations_sid.MAF"
cores = 9
region.of.interest = NULL

chrOrder <- c(paste("chr", 1:22, sep = ""), "chrX")
seqi = GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[GenomeInfoDb::seqnames(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[1:23]]
seqnames = GenomeInfoDb::seqnames(GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens))[1:23]

mask.regions = readRDS(mask.regions.file)
mask.regions = mask.regions[as.character(GenomeInfoDb::seqnames(mask.regions)) %in% seqnames]

maf.snv <- maf.to.granges(snv.mutations.file)
maf.snv = maf.snv[as.character(GenomeInfoDb::seqnames(maf.snv)) %in% seqnames]
GenomeInfoDb::seqlevels(maf.snv) = as.character(unique(GenomeInfoDb::seqnames(maf.snv)))

maf.snv2 <- maf.to.granges(snv.mutations.file2)
maf.snv2 = maf.snv2[as.character(GenomeInfoDb::seqnames(maf.snv2)) %in% seqnames]
maf.ind.snv = GenomicRanges::split(maf.snv2, maf.snv2$sid)
ind.mut.count.snv = sapply(maf.ind.snv, length)

maf.masked.snv <- maf.snv[-S4Vectors::subjectHits(IRanges::findOverlaps(mask.regions, maf.snv))]
dupl.snv = duplicated(maf.masked.snv)
maf.uniq.snv = maf.masked.snv[!dupl.snv, ]

mut.regions = maf.uniq.snv + 10
names(mut.regions) = paste("Mutation", c(1:length(mut.regions)), sep = "")

rm(list = c("maf.uniq.snv", "mask.regions"))
gc()

roi = mut.regions
genome.size = 2533374732
min.count = 2

print(paste("Using ", length(roi), " ROIs from input", sep = ""))

print(">> Intersecting ROIs and MAF ...")
maf.ovl <- IRanges::findOverlaps(roi, maf.snv, ignore.strand = TRUE)
maf.ovl.m = IRanges::as.matrix(maf.ovl)

nsamples = length(unique(maf.snv$sid))
roi.count.mutated = tapply(maf.snv$sid[maf.ovl.m[ ,2]], names(roi)[maf.ovl.m[ ,1]],function(s) length(unique(s)))
roi.mutated = names(roi.count.mutated)[roi.count.mutated >= min.count]
print(paste("Using ", length(roi.mutated), " ROIs mutated in >=", min.count, " samples", sep = ""))

rois.to.run = roi.mutated

results = c()

sid=unique(maf.snv2$sid)

p.bg = parallel::mclapply (sid, function(s) {
  
  p = rep(ind.mut.count.snv[s] / 2533374732, 21)
  p.roi.snv = 1 - prod(1 - p)   
  
  return(p.roi.snv)
  
}, mc.cores = 4 )
p.bg = unlist(p.bg)

process.single.roi <- function(x) {
  
  roi.progress <- which(rois.to.run == x)
  if ((roi.progress %% ceiling(length(rois.to.run) / 5000)) == 0) {
    
    print(paste("Progress : ", roi.progress, "/", length(rois.to.run), sep = ""))
    
  }
  
  x.idx = which(names(roi) == x)[1]
  k = length(unique(maf.snv$sid[maf.ovl.m[maf.ovl.m[ ,1] == x.idx, 2]]))
  pval = poibin::ppoibin(length(p.bg) - k, 1 - p.bg, method = 'RF')
  c(x, pval, 21, mean(p.bg), k)
  
}

results = parallel::mclapply(rois.to.run, function(xr) { process.single.roi(xr) }, mc.cores = cores, mc.preschedule = FALSE, mc.silent = FALSE)

results.error = sapply(results, function(x) { length(x) == 1 } )
print(rois.to.run[which(results.error)])
print(results[results.error])
results = results[!results.error]

results = do.call(rbind,results)
rownames(results) = results[ ,1]
results = results[ ,-1, drop = FALSE]
class(results) <- "numeric"
fdr = p.adjust(results[ ,1], method = 'BH') * genome.size / nrow(results)
fdr = sapply(fdr, function(x) min(x, 1))  
results = cbind(results, fdr)
colnames(results) = c('pval', 'length', 'p.bg', 'k', 'fdr')
results = results[order(results[ ,'pval']), , drop = FALSE]

mut.rec = results
mut.regions2 = mut.regions[names(mut.regions) %in% rownames(mut.rec)]
mut.rec.hotspot = data.frame(chrom = as.character(GenomeInfoDb::seqnames(mut.regions2[rownames(mut.rec)])), start = GenomicRanges::start(mut.regions2[rownames(mut.rec)]), end = GenomicRanges::end(mut.regions2[rownames(mut.rec)]), mut.rec)

write.table(mut.rec.hotspot, file = "wgs_hotspots_null2.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = TRUE)

mut.rec.hotspot2 = mut.rec.hotspot
mut.rec.hotspot2$ID = as.character(rownames(mut.rec.hotspot2))
mut.rec.hotspot2 = with(mut.rec.hotspot2, GenomicRanges::GRanges(chrom, IRanges::IRanges(start, end), pval = pval, length = length, p.bg = p.bg, k = k, fdr = fdr, ID = ID))
hotspots = IRanges::reduce(mut.rec.hotspot2)
hotspots$hs = paste("hs", 1:length(hotspots), sep = "")
ovl.mut = IRanges::findOverlaps(maf.snv, hotspots)
hotspots2 = hotspots[S4Vectors::subjectHits(ovl.mut)]
hotspots2$sample = maf.snv[S4Vectors::queryHits(ovl.mut)]$sid
hotspots2 = GenomicRanges::as.data.frame(hotspots2)
hotspots2 = aggregate(sample ~ hs, hotspots2, FUN = function(k) length(unique(k)))
colnames(hotspots2)[2] = "k"
rownames(hotspots2) = hotspots2$hs
hotspots$k = 0
for (i in 1:length(hotspots)) {
  # print(i)
  hotspots$k[i] = hotspots2[which(hotspots2$hs == hotspots$hs[i]), "k"]
  
}

ovl = IRanges::findOverlaps(mut.rec.hotspot2, hotspots)
mut.rec.hotspot2 = mut.rec.hotspot2[S4Vectors::queryHits(ovl)]
mut.rec.hotspot2$hs = hotspots[S4Vectors::subjectHits(ovl)]$hs
mut.rec.hotspot2$region.start = IRanges::start(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$region.end = IRanges::end(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$new.k = hotspots[S4Vectors::subjectHits(ovl)]$k
mut.rec.hotspot2 = GenomicRanges::as.data.frame(mut.rec.hotspot2)
mut.rec.hotspot2 = mut.rec.hotspot2[order(mut.rec.hotspot2$pval, decreasing = FALSE), ]
mut.rec.hotspot2 = mut.rec.hotspot2[!duplicated(mut.rec.hotspot2$hs), ]
mut.rec.hotspot2 = mut.rec.hotspot2[ ,c("seqnames", "region.start", "region.end", "pval", "length", "p.bg", "new.k", "fdr", "ID")]
mut.rec.hotspot2$length = mut.rec.hotspot2$region.end - mut.rec.hotspot2$region.start + 1
colnames(mut.rec.hotspot2) = c(colnames(mut.rec.hotspot), "ID")
rownames(mut.rec.hotspot2) = mut.rec.hotspot2$ID
mut.rec.hotspot2 = mut.rec.hotspot2[ ,-ncol(mut.rec.hotspot2)]

write.table(mut.rec.hotspot, file = "wgs_hotspots_null2_merged.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = TRUE)
```

```{r, eval = FALSE}
# Run poisson binomial + replication timing
MutSpot(run.to = c(5.1, 5.2, 5.3, 6, 7),
        snv.mutations = "gastric_snv_mutations_sid.MAF",
        cores = 6,
        drop = FALSE,
        genomic.features = "genomic_features_genome_APO.txt") # wgs_hotspots_null3_merged.tsv
```

```{r, eval = FALSE}
# Run poisson binomial + replication timing + local mutation rate
MutSpot(run.to = c(5.1, 5.2, 5.3, 6, 7),
        snv.mutations = "gastric_snv_mutations_sid.MAF",
        cores = 6,
        drop = FALSE,
        genomic.features = "genomic_features_genome_APO.txt") # wgs_hotspots_null4_merged.tsv
```

```{r}
a1 = read.delim("wgs_hotspots_null1_merged.tsv", stringsAsFactors = FALSE)
a2 = read.delim("wgs_hotspots_null2_merged.tsv", stringsAsFactors = FALSE)
a3 = read.delim("wgs_hotspots_null3_merged.tsv", stringsAsFactors = FALSE)
a4 = read.delim("wgs_hotspots_null4_merged.tsv", stringsAsFactors = FALSE)
a5 = read.delim("snv_wgs_hotspots_merged.tsv", stringsAsFactors = FALSE)

df = data.frame(counts = c(sum(a1$fdr <= 0.05), sum(a2$fdr <= 0.05), sum(a3$fdr <= 0.05), sum(a4$fdr <= 0.05), sum(a5$fdr <= 0.05)), model = c("a", "b", "c", "d", "e"))
df$group = c(rep("g1", 4), "g2")
df$model = as.character(df$model)
df$model = factor(df$model, levels = c("e", "d", "c", "b", "a"))

ggplot(data = df, aes(x = model, y = counts, fill = group)) + xlab("Model") + ylab("Number of significant hotspots") +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(angle = 90, hjust = 1,size = 20)) +
  scale_fill_manual(values = c("#FFB266", "#E42F9B")) + theme(legend.position = "none") + coord_flip()
```

## Figure E
Barplot for gastric CTCF binding sites SNV model comparison
```{r, eval = FALSE}
# Run simple binomial model
mask.regions.file = "mask_regions.RDS"
snv.mutations.file = "SNV_region.MAF"
snv.mutations.file2 = "gastric_snv_mutations_sid.MAF"
cores = 9
region.of.interest = "gastric_ctcf_motif.bed"

chrOrder <- c(paste("chr", 1:22, sep = ""), "chrX")
seqi = GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[GenomeInfoDb::seqnames(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[1:23]]
seqnames = GenomeInfoDb::seqnames(GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens))[1:23]

mask.regions = readRDS(mask.regions.file)
mask.regions = mask.regions[as.character(GenomeInfoDb::seqnames(mask.regions)) %in% seqnames]

maf.snv <- maf.to.granges(snv.mutations.file)
maf.snv = maf.snv[as.character(GenomeInfoDb::seqnames(maf.snv)) %in% seqnames]
GenomeInfoDb::seqlevels(maf.snv) = as.character(unique(GenomeInfoDb::seqnames(maf.snv)))

maf.snv2 <- maf.to.granges(snv.mutations.file2)
maf.snv2 = maf.snv2[as.character(GenomeInfoDb::seqnames(maf.snv2)) %in% seqnames]
maf.ind.snv = GenomicRanges::split(maf.snv2, maf.snv2$sid)
ind.mut.count.snv = sapply(maf.ind.snv, length)

maf.masked.snv <- maf.snv[-S4Vectors::subjectHits(IRanges::findOverlaps(mask.regions, maf.snv))]
dupl.snv = duplicated(maf.masked.snv)
maf.uniq.snv = maf.masked.snv[!dupl.snv, ]

mut.regions = maf.uniq.snv + 10
names(mut.regions) = paste("Mutation", c(1:length(mut.regions)), sep = "")

rm(list = c("maf.uniq.snv", "mask.regions"))
gc()

regions = bed.to.granges(region.of.interest)
regions = regions[as.character(GenomeInfoDb::seqnames(regions)) %in% as.character(GenomeInfoDb::seqnames(seqi))]
names(regions) = paste("Region", c(1:length(regions)), sep = "")

mask.regions = readRDS(mask.regions.file)

maf.masked.regions <-regions[-S4Vectors::subjectHits(IRanges::findOverlaps(mask.regions, regions))]

roi = mut.regions
genome.size = sum(GenomicRanges::width(GenomicRanges::reduce(maf.masked.regions)))

print(paste("Using ", length(roi), " ROIs from input", sep = ""))

print(">> Intersecting ROIs and MAF ...")
maf.ovl <- IRanges::findOverlaps(roi, maf.snv, ignore.strand = TRUE)
maf.ovl.m = IRanges::as.matrix(maf.ovl)
min.count = 2

nsamples = length(unique(maf.snv$sid))
roi.count.mutated = tapply(maf.snv$sid[maf.ovl.m[ ,2]], names(roi)[maf.ovl.m[ ,1]],function(s) length(unique(s)))
roi.mutated = names(roi.count.mutated)[roi.count.mutated >= min.count]
print(paste("Using ", length(roi.mutated), " ROIs mutated in >=", min.count, " samples", sep = ""))

rois.to.run = roi.mutated

results = c()

sid = unique(maf.snv2$sid)

p.bg = parallel::mclapply (sid, function(s) {
  
  p = rep(length(maf.snv2) / (2533374732 * (length(unique(maf.snv2$sid)))), 21)
  p.roi.snv = 1 - prod(1 - p)   
  
  return(p.roi.snv)
  
}, mc.cores = 9 )
p.bg = unlist(p.bg)

process.single.roi <- function(x) {
  
  roi.progress <- which(rois.to.run == x)
  if ((roi.progress %% ceiling(length(rois.to.run) / 100)) == 0) {
    
    print(paste("Progress : ", roi.progress, "/", length(rois.to.run), sep = ""))
    
  }
  
  x.idx = which(names(roi) == x)[1]
  k = length(unique(maf.snv$sid[maf.ovl.m[maf.ovl.m[ ,1] == x.idx, 2]]))
  
  pval = 1 - pbinom(k - 1, 168, unique(p.bg))
  
  c(x, pval, 21, mean(p.bg), k)

}

results = parallel::mclapply(rois.to.run, function(xr) { process.single.roi(xr) }, mc.cores = cores, mc.preschedule = FALSE, mc.silent = FALSE)

results.error = sapply(results, function(x) { length(x) == 1 } )
print(rois.to.run[which(results.error)])
print(results[results.error])
results = results[!results.error]

results = do.call(rbind,results)
rownames(results) = results[ ,1]
results = results[ ,-1, drop = FALSE]
class(results) <- "numeric"
fdr = p.adjust(results[ ,1], method = 'BH') * genome.size / nrow(results)
fdr = sapply(fdr, function(x) min(x, 1))  
results = cbind(results, fdr)
colnames(results) = c('pval', 'length', 'p.bg', 'k', 'fdr')
results = results[order(results[ ,'pval']), , drop = FALSE]

mut.rec = results
mut.regions2 = mut.regions[names(mut.regions) %in% rownames(mut.rec)]
mut.rec.hotspot = data.frame(chrom = as.character(GenomeInfoDb::seqnames(mut.regions2[rownames(mut.rec)])), start = GenomicRanges::start(mut.regions2[rownames(mut.rec)]), end = GenomicRanges::end(mut.regions2[rownames(mut.rec)]), mut.rec)

write.table(mut.rec.hotspot, file="ctcf_hotspots_null1.tsv",sep="\t",quote=FALSE,row.names=TRUE,col.names=TRUE)

mut.rec.hotspot2 = mut.rec.hotspot
mut.rec.hotspot2$ID = as.character(rownames(mut.rec.hotspot2))
mut.rec.hotspot2 = with(mut.rec.hotspot2, GenomicRanges::GRanges(chrom, IRanges::IRanges(start, end), pval = pval, length = length, p.bg = p.bg, k = k, fdr = fdr, ID = ID))
hotspots = IRanges::reduce(mut.rec.hotspot2)
hotspots$hs = paste("hs", 1:length(hotspots), sep = "")
ovl.mut = IRanges::findOverlaps(maf.snv, hotspots)
hotspots2 = hotspots[S4Vectors::subjectHits(ovl.mut)]
hotspots2$sample = maf.snv[S4Vectors::queryHits(ovl.mut)]$sid
hotspots2 = GenomicRanges::as.data.frame(hotspots2)
hotspots2 = aggregate(sample ~ hs, hotspots2, FUN = function(k) length(unique(k)))
colnames(hotspots2)[2] = "k"
rownames(hotspots2) = hotspots2$hs
hotspots$k = 0
for (i in 1:length(hotspots)) {
  # print(i)
  hotspots$k[i] = hotspots2[which(hotspots2$hs == hotspots$hs[i]), "k"]
  
}

ovl = IRanges::findOverlaps(mut.rec.hotspot2, hotspots)
mut.rec.hotspot2 = mut.rec.hotspot2[S4Vectors::queryHits(ovl)]
mut.rec.hotspot2$hs = hotspots[S4Vectors::subjectHits(ovl)]$hs
mut.rec.hotspot2$region.start = IRanges::start(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$region.end = IRanges::end(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$new.k = hotspots[S4Vectors::subjectHits(ovl)]$k
mut.rec.hotspot2 = GenomicRanges::as.data.frame(mut.rec.hotspot2)
mut.rec.hotspot2 = mut.rec.hotspot2[order(mut.rec.hotspot2$pval, decreasing = FALSE), ]
mut.rec.hotspot2 = mut.rec.hotspot2[!duplicated(mut.rec.hotspot2$hs), ]
mut.rec.hotspot2 = mut.rec.hotspot2[ ,c("seqnames", "region.start", "region.end", "pval", "length", "p.bg", "new.k", "fdr", "ID")]
mut.rec.hotspot2$length = mut.rec.hotspot2$region.end - mut.rec.hotspot2$region.start + 1
colnames(mut.rec.hotspot2) = c(colnames(mut.rec.hotspot), "ID")
rownames(mut.rec.hotspot2) = mut.rec.hotspot2$ID
mut.rec.hotspot2 = mut.rec.hotspot2[ ,-ncol(mut.rec.hotspot2)]

write.table(mut.rec.hotspot, file = "ctcf_hotspots_null1_merged.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = TRUE)
```

```{r, eval = FALSE}
# Run poisson binomial model
mask.regions.file = "mask_regions.RDS"
snv.mutations.file = "SNV_region.MAF"
snv.mutations.file2 = "gastric_snv_mutations_sid.MAF"
cores = 9
region.of.interest = "gastric_ctcf_motif.bed"

chrOrder <- c(paste("chr", 1:22, sep = ""), "chrX")
seqi = GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[GenomeInfoDb::seqnames(BSgenome.Hsapiens.UCSC.hg19::Hsapiens)[1:23]]
seqnames = GenomeInfoDb::seqnames(GenomeInfoDb::seqinfo(BSgenome.Hsapiens.UCSC.hg19::Hsapiens))[1:23]

mask.regions = readRDS(mask.regions.file)
mask.regions = mask.regions[as.character(GenomeInfoDb::seqnames(mask.regions)) %in% seqnames]

maf.snv <- maf.to.granges(snv.mutations.file)
maf.snv = maf.snv[as.character(GenomeInfoDb::seqnames(maf.snv)) %in% seqnames]
GenomeInfoDb::seqlevels(maf.snv) = as.character(unique(GenomeInfoDb::seqnames(maf.snv)))

maf.snv2 <- maf.to.granges(snv.mutations.file2)
maf.snv2 = maf.snv2[as.character(GenomeInfoDb::seqnames(maf.snv2)) %in% seqnames]
maf.ind.snv = GenomicRanges::split(maf.snv2, maf.snv2$sid)
ind.mut.count.snv = sapply(maf.ind.snv, length)

maf.masked.snv <- maf.snv[-S4Vectors::subjectHits(IRanges::findOverlaps(mask.regions, maf.snv))]
dupl.snv = duplicated(maf.masked.snv)
maf.uniq.snv = maf.masked.snv[!dupl.snv, ]

mut.regions = maf.uniq.snv + 10
names(mut.regions) = paste("Mutation", c(1:length(mut.regions)), sep = "")

rm(list = c("maf.uniq.snv", "mask.regions"))
gc()

regions = bed.to.granges(region.of.interest)
regions = regions[as.character(GenomeInfoDb::seqnames(regions)) %in% as.character(GenomeInfoDb::seqnames(seqi))]
names(regions) = paste("Region", c(1:length(regions)), sep = "")

mask.regions = readRDS(mask.regions.file)

maf.masked.regions <-regions[-S4Vectors::subjectHits(IRanges::findOverlaps(mask.regions, regions))]

roi = mut.regions
genome.size = sum(GenomicRanges::width(GenomicRanges::reduce(maf.masked.regions)))
min.count = 2

print(paste("Using ", length(roi), " ROIs from input", sep = ""))

print(">> Intersecting ROIs and MAF ...")
maf.ovl <- IRanges::findOverlaps(roi, maf.snv, ignore.strand = TRUE)
maf.ovl.m = IRanges::as.matrix(maf.ovl)

nsamples = length(unique(maf.snv$sid))
roi.count.mutated = tapply(maf.snv$sid[maf.ovl.m[ ,2]], names(roi)[maf.ovl.m[ ,1]],function(s) length(unique(s)))
roi.mutated = names(roi.count.mutated)[roi.count.mutated >= min.count]
print(paste("Using ", length(roi.mutated), " ROIs mutated in >=", min.count, " samples", sep = ""))

rois.to.run = roi.mutated

results = c()

sid=unique(maf.snv2$sid)

p.bg = parallel::mclapply (sid, function(s) {

  p = rep(ind.mut.count.snv[s] / 2533374732, 21)
  p.roi.snv = 1 - prod(1 - p)

  return(p.roi.snv)

}, mc.cores = 9 )
p.bg = unlist(p.bg)

process.single.roi <- function(x) {

  roi.progress <- which(rois.to.run == x)
  if ((roi.progress %% ceiling(length(rois.to.run) / 100)) == 0) {

    print(paste("Progress : ", roi.progress, "/", length(rois.to.run), sep = ""))

  }

  x.idx = which(names(roi) == x)[1]
  k = length(unique(maf.snv$sid[maf.ovl.m[maf.ovl.m[ ,1] == x.idx, 2]]))
  pval = poibin::ppoibin(length(p.bg) - k, 1 - p.bg, method = 'RF')
  c(x, pval, 21, mean(p.bg), k)

  }

results = parallel::mclapply(rois.to.run, function(xr) { process.single.roi(xr) }, mc.cores = cores, mc.preschedule = FALSE, mc.silent = FALSE)

results.error = sapply(results, function(x) { length(x) == 1 } )
print(rois.to.run[which(results.error)])
print(results[results.error])
results = results[!results.error]

results = do.call(rbind,results)
rownames(results) = results[ ,1]
results = results[ ,-1, drop = FALSE]
class(results) <- "numeric"
fdr = p.adjust(results[ ,1], method = 'BH') * genome.size / nrow(results)
fdr = sapply(fdr, function(x) min(x, 1))  
results = cbind(results, fdr)
colnames(results) = c('pval', 'length', 'p.bg', 'k', 'fdr')
results = results[order(results[ ,'pval']), , drop = FALSE]

mut.rec = results
mut.regions2 = mut.regions[names(mut.regions) %in% rownames(mut.rec)]
mut.rec.hotspot = data.frame(chrom = as.character(GenomeInfoDb::seqnames(mut.regions2[rownames(mut.rec)])), start = GenomicRanges::start(mut.regions2[rownames(mut.rec)]), end = GenomicRanges::end(mut.regions2[rownames(mut.rec)]), mut.rec)

write.table(mut.rec.hotspot, file = "ctcf_hotspots_null2.tsv",sep="\t",quote=FALSE,row.names=TRUE,col.names=TRUE)

mut.rec.hotspot2 = mut.rec.hotspot
mut.rec.hotspot2$ID = as.character(rownames(mut.rec.hotspot2))
mut.rec.hotspot2 = with(mut.rec.hotspot2, GenomicRanges::GRanges(chrom, IRanges::IRanges(start, end), pval = pval, length = length, p.bg = p.bg, k = k, fdr = fdr, ID = ID))
hotspots = IRanges::reduce(mut.rec.hotspot2)
hotspots$hs = paste("hs", 1:length(hotspots), sep = "")
ovl.mut = IRanges::findOverlaps(maf.snv, hotspots)
hotspots2 = hotspots[S4Vectors::subjectHits(ovl.mut)]
hotspots2$sample = maf.snv[S4Vectors::queryHits(ovl.mut)]$sid
hotspots2 = GenomicRanges::as.data.frame(hotspots2)
hotspots2 = aggregate(sample ~ hs, hotspots2, FUN = function(k) length(unique(k)))
colnames(hotspots2)[2] = "k"
rownames(hotspots2) = hotspots2$hs
hotspots$k = 0
for (i in 1:length(hotspots)) {
  # print(i)
  hotspots$k[i] = hotspots2[which(hotspots2$hs == hotspots$hs[i]), "k"]
  
}

ovl = IRanges::findOverlaps(mut.rec.hotspot2, hotspots)
mut.rec.hotspot2 = mut.rec.hotspot2[S4Vectors::queryHits(ovl)]
mut.rec.hotspot2$hs = hotspots[S4Vectors::subjectHits(ovl)]$hs
mut.rec.hotspot2$region.start = IRanges::start(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$region.end = IRanges::end(hotspots[S4Vectors::subjectHits(ovl)])
mut.rec.hotspot2$new.k = hotspots[S4Vectors::subjectHits(ovl)]$k
mut.rec.hotspot2 = GenomicRanges::as.data.frame(mut.rec.hotspot2)
mut.rec.hotspot2 = mut.rec.hotspot2[order(mut.rec.hotspot2$pval, decreasing = FALSE), ]
mut.rec.hotspot2 = mut.rec.hotspot2[!duplicated(mut.rec.hotspot2$hs), ]
mut.rec.hotspot2 = mut.rec.hotspot2[ ,c("seqnames", "region.start", "region.end", "pval", "length", "p.bg", "new.k", "fdr", "ID")]
mut.rec.hotspot2$length = mut.rec.hotspot2$region.end - mut.rec.hotspot2$region.start + 1
colnames(mut.rec.hotspot2) = c(colnames(mut.rec.hotspot), "ID")
rownames(mut.rec.hotspot2) = mut.rec.hotspot2$ID
mut.rec.hotspot2 = mut.rec.hotspot2[ ,-ncol(mut.rec.hotspot2)]

write.table(mut.rec.hotspot, file = "ctcf_hotspots_null2_merged.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = TRUE)
```

```{r, eval = FALSE}
# Run poisson binomial + replication timing
MutSpot(
  run.to = c(5.1, 5.2, 5.3, 6, 7),
  snv.mutations = "gastric_snv_mutations_sid.MAF",
  region.of.interest = "gastric_ctcf_motif.bed", 
  cores = 9, 
  genomic.features = "genomic_features_ctcf_APO.txt",
  drop = FALSE
) # ctcf_hotspots_null3_merged.tsv
```

```{r, eval = FALSE}
# Run poisson binomial + replication timing + local mutation rate
MutSpot(
  run.to = c(5.1, 5.2, 5.3, 6, 7),
  snv.mutations = "gastric_snv_mutations_sid.MAF",
  region.of.interest = "gastric_ctcf_motif.bed", 
  cores = 9, 
  genomic.features = "genomic_features_ctcf_APO.txt",
  drop = FALSE
) # ctcf_hotspots_null4_merged.tsv
```

```{r}
a1 = read.delim("ctcf_hotspots_null1_merged.tsv", stringsAsFactors = FALSE)
a2 = read.delim("ctcf_hotspots_null2_merged.tsv", stringsAsFactors = FALSE)
a3 = read.delim("ctcf_hotspots_null3_merged.tsv", stringsAsFactors = FALSE)
a4 = read.delim("ctcf_hotspots_null4_merged.tsv", stringsAsFactors = FALSE)
a5 = read.delim("snv_ctcf_hotspots_merged.tsv", stringsAsFactors = FALSE)

df = data.frame(counts = c(sum(a1$fdr <= 0.05), sum(a2$fdr <= 0.05), sum(a3$fdr <= 0.05), sum(a4$fdr <= 0.05), sum(a5$fdr <= 0.05)), model = c("a", "b", "c", "d", "e"))
df$group = c(rep("g1", 4), "g2")
df$model = as.character(df$model)
df$model = factor(df$model, levels = c("e", "d", "c", "b", "a"))

ggplot(data = df, aes(x = model, y = counts, fill = group)) + xlab("Model") + ylab("Number of significant hotspots") +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(angle = 90, hjust = 1, size = 20)) +
  scale_fill_manual(values = c("#FFB266", "#E42F9B")) + theme(legend.position = "none") + coord_flip()
```
